#!/bin/sh
#
# @name Reconrobot (Water version Configuration)
#
# @type Vectored 6 DOF UUV
# @class Underwater Robot
#
# @output Motor1 bow starboard canted thruster (60.00° from horizontal, thrust down-port)
# @output Motor2 bow port canted thruster (60.00° from horizontal, thrust down-starboard)
# @output Motor3 stern starboard canted thruster (60.06° from horizontal, thrust up-starboard)
# @output Motor4 stern port canted thruster (60.06° from horizontal, thrust up-port)
# @output Motor5 mid starboard forward thruster (surge)
# @output Motor6 mid port forward thruster (surge)
# @output Motor7 forward port lateral thruster (thrust starboard)
# @output Motor8 aft port lateral thruster (thrust starboard)
#
# @maintainer Nathaniel Asiak <asiaknathan@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

# param set-default MAV_1_CONFIG 102

param set-default BAT1_A_PER_V 37.8798
param set-default BAT1_CAPACITY 18000
param set-default BAT1_V_DIV 11
param set-default BAT1_N_CELLS 4
param set-default BAT_V_OFFS_CURR 0.33

# Set parameters using `param` utility for SITL
param set-default CA_AIRFRAME 7
param set-default CA_METHOD 0
param set-default MAV_TYPE 12

# Board rotation: set to direct replacement of RPi with PX4
#       with forward facing vehicle forward
# param set-default SENS_BOARD_ROT 16

# Set proper failsafes
param set-default COM_ACT_FAIL_ACT 0
param set-default COM_LOW_BAT_ACT 0
param set-default NAV_DLL_ACT 0
param set-default GF_ACTION 1
param set-default NAV_RCL_ACT 1
param set-default COM_POSCTL_NAVL 2

# disable attitude failure detection
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0

param set-default CA_ROTOR_COUNT 8
param set-default CA_R_REV 255

param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY -0.5000
param set-default CA_ROTOR0_AZ 0.8660
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 0.4293
param set-default CA_ROTOR0_PY 0.1342
param set-default CA_ROTOR0_PZ -0.1007

param set-default CA_ROTOR1_AX 0
param set-default CA_ROTOR1_AY 0.5000
param set-default CA_ROTOR1_AZ 0.8660
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0.4293
param set-default CA_ROTOR1_PY -0.1369
param set-default CA_ROTOR1_PZ -0.1002

param set-default CA_ROTOR2_AX 0
param set-default CA_ROTOR2_AY 0.4991
param set-default CA_ROTOR2_AZ -0.8665
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX -0.4567
param set-default CA_ROTOR2_PY 0.1326
param set-default CA_ROTOR2_PZ -0.0996

param set-default CA_ROTOR3_AX 0
param set-default CA_ROTOR3_AY -0.4991
param set-default CA_ROTOR3_AZ -0.8665
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX -0.4567
param set-default CA_ROTOR3_PY -0.1384
param set-default CA_ROTOR3_PZ -0.0996

param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_KM 0
param set-default CA_ROTOR4_PX 0.0773
param set-default CA_ROTOR4_PY 0.1350
param set-default CA_ROTOR4_PZ 0.1183

param set-default CA_ROTOR5_AX 1
param set-default CA_ROTOR5_AY 0
param set-default CA_ROTOR5_AZ 0
param set-default CA_ROTOR5_KM 0
param set-default CA_ROTOR5_PX 0.0773
param set-default CA_ROTOR5_PY -0.1430
param set-default CA_ROTOR5_PZ 0.1183

param set-default CA_ROTOR6_AX 0
param set-default CA_ROTOR6_AY 1
param set-default CA_ROTOR6_AZ 0
param set-default CA_ROTOR6_KM 0
param set-default CA_ROTOR6_PX 0.2743
param set-default CA_ROTOR6_PY -0.0945
param set-default CA_ROTOR6_PZ 0.1793

param set-default CA_ROTOR7_AX 0
param set-default CA_ROTOR7_AY 1
param set-default CA_ROTOR7_AZ 0
param set-default CA_ROTOR7_KM 0
param set-default CA_ROTOR7_PX -0.3027
param set-default CA_ROTOR7_PY -0.0945
param set-default CA_ROTOR7_PZ 0.1793

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108

param set-default PWM_MAIN_MIN1 253
param set-default PWM_MAIN_MIN2 253
param set-default PWM_MAIN_MIN3 253
param set-default PWM_MAIN_MIN4 253
param set-default PWM_MAIN_MIN5 253
param set-default PWM_MAIN_MIN6 253
param set-default PWM_MAIN_MIN7 253
param set-default PWM_MAIN_MIN8 253

param set-default PWM_MAIN_MAX1 2275
param set-default PWM_MAIN_MAX2 2275
param set-default PWM_MAIN_MAX3 2275
param set-default PWM_MAIN_MAX4 2275
param set-default PWM_MAIN_MAX5 2275
param set-default PWM_MAIN_MAX6 2275
param set-default PWM_MAIN_MAX7 2275
param set-default PWM_MAIN_MAX8 2275

param set-default PWM_MAIN_DIS1 1250
param set-default PWM_MAIN_DIS2 1250
param set-default PWM_MAIN_DIS3 1250
param set-default PWM_MAIN_DIS4 1250
param set-default PWM_MAIN_DIS5 1250
param set-default PWM_MAIN_DIS6 1250
param set-default PWM_MAIN_DIS7 1250
param set-default PWM_MAIN_DIS8 1250


#Assign AUX motors
param set-default PWM_AUX_FUNC1 301
param set-default PWM_AUX_FUNC2 302
param set-default PWM_AUX_FUNC3 0
param set-default PWM_AUX_FUNC4 0
param set-default PWM_AUX_FUNC5 0
param set-default PWM_AUX_FUNC6 0
param set-default PWM_AUX_FUNC7 0
param set-default PWM_AUX_FUNC8 0

#set PWM rates for AUX
param set-default PWM_AUX_TIM0 400 #AUX 1-2
param set-default PWM_AUX_TIM1 400 #AUX 3-4
